version: '3.1'

services:
  api:
    image: todo:latest
    build: server
    restart: always
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - HOST=0.0.0.0
      - MONGO="mongodb://mongo:27017/todo?retryWrites=true"
      - SECRET="Anyway the wind blows, doesn't really matter to me, to me"
  mongo:
    image: mongo
    restart: always